#%RAML 1.0
baseUri: https://anypoint.mulesoft.com/mocking/api/v1/links/96f78808-ba06-481d-96ee-a7d2b7397372/ # 
version: v1
title: American Flights API

types:
  AmericanFlight: !include exchange_modules/68ef9520-24e9-4cf2-b2f5-620025690913/training-american-flight-data-type/1.0.1/AmericanFlightDataType.raml

/flights:
  get:
    queryParameters:
      destination:
        required: false
        enum: 
          - SFO
          - LAX
          - CLE
    responses:
      200:
        body:
          application/json:
            example: 
              [{
                  "ID": 1,
                  "code": "ER38sd",
                  "price": 400,
                  "departureDate": "2017/07/26",
                  "origin": "CLE",
                  "destination": "SFO",
                  "emptySeats": 0,
                  "plane":{
                    "type": "Boeing 737",
                    "totalSeats": 150
                  }                    
                },
                {

                    "ID": 2,
                    "code": "ER45if",
                    "price": 540.99,
                    "departureDate": "2017/07/27",
                    "origin": "SFO",
                    "destination": "ORD",
                    "emptySeats": 54,
                    "plane":{
                      "type": "Boeing 777",
                      "totalSeats": 300
                    } 
                }]
              
      
  post:
    body:
        application/json:
          type: AmericanFlight
          example: 
              {
                   "ID": 1, 
                    "code": "ER38sd",
                    price: 400,
                    "departureDate": "2017/07/26",
                    "origin": "CLE",
                    "destination": "SFO",
                    "emptySeats": 0,
                    "plane":{
                        "type": "Boeing 737",
                        "totalSeats": 150
                        
                    } 
                      
              }
            

    responses:
      201:
        body:
          application/json:
            example:
              message: Flight Added (Not really)
            
  delete:
    body:
        application/json:
          type: AmericanFlight
          
    responses:
      200:
        body:
          application/json:
            example:
              message: Flight Deleted (Not really)

  /{ID}:
    get:
     responses:
      200:
        body:
          application/json:
            type: AmericanFlight
            example: 
              {
                   "ID": 1, 
                    "code": "ER38sd",
                    price: 400,
                    "departureDate": "2017/07/26",
                    "origin": "CLE",
                    "destination": "SFO",
                    "emptySeats": 0,
                    "plane":{
                        "type": "Boeing 737",
                        "totalSeats": 150
                        
                    } 
                      
              }
                 
              
      